#include <uapi/linux/ptrace.h>

// The epoll_pwait / epoll_pwait2 tracepoint argument structs (generated by BCC
// from the kernel tracepoint format) reference sigset_t, which the default
// includes don't provide. Define a minimal version unconditionally — it's an
// unused typedef when only epoll_wait is traced, and harmless otherwise.
typedef struct { unsigned long sig[1]; } sigset_t;

struct event_t {
    u64 start_ns;
    u64 end_ns;
    u32 pid;
    u32 tid;
};

BPF_HASH(callback_start, u32, u64);
BPF_PERF_OUTPUT(events);

// One sys_enter/sys_exit probe pair per available epoll variant is generated in
// detector.py (_EPOLL_PROBE_TEMPLATE) and substituted here. We trace the whole
// epoll family rather than a single guessed syscall: which variant an event
// loop enters depends on its libc and implementation — glibc routes
// epoll_wait() through the epoll_pwait syscall, and uvloop/libuv call
// epoll_pwait (or epoll_pwait2) directly — so hard-wiring epoll_wait silently
// misses every stall on loops that use another variant. All pairs share the
// callback_start map, so a thread is timed across exit→enter regardless of
// which variant it uses.
__EPOLL_PROBES__
